baseurl = "https://babil.xyz"
title = "BSYY"
languageCode = "tr"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "https://babil.xyz"
canonifyurls = true
author = "O"
theme = "simple-style"
googleAnalytics = "UA-122786587-2"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = true
  twitter_username = "osmanorhan"
  paginate = true
  googleSiteVerification = "lc0xPWSMzXoIyfd1S57OuIt5df4Lntjg4hE_79LFo_A"
  author = "O"